### PR TITLE
fixed localization of doctype naming in overlay content type selector

### PR DESCRIPTION
**Pull request by frederikreher**
Previously document type names weren't translated as the doctype names were just returned directly from the InnerContentApiController. 
I've implemented a basecontroller with a translation method to make sure the naming is correct.

### CODE REVIEW

**Comment by frederikreher** [comment]
@mattbrailsford @leekelleher

**Comment by leekelleher** [comment]
Hi @frederikreher, thanks for the PR! _(I've been on vacation, hence the delay in my reply)._

I'm happy with the doctype name localization being fixed, but I'm not sure why it needs to be in a base class?  If you could add the `TranslateItem` to the `InnerContentApiController` itself (and make it private/internal), then that'd be great.  We could merge it in.  Thanks! 😃

**Comment by frederikreher** [comment]
@leekelleher 

I'm not sure what is was thinking at that point, maybe just blindly copying the implementation from core. :-) I've moved the method into the `InnerContentApiController` now - not sure if you'd like the properties above the methods?

**Comment by leekelleher** [comment]
Cool, thanks @frederikreher, it's very much appreciated. Merging in now.

**Pull request merged**
