### PR TITLE
 Added data-element to property

### PR DESCRIPTION
**Pull request by skartknet**

### CODE REVIEW

**Comment by leekelleher** [comment]
@skartknet Thank you for the pull request.

What does `data-element` do?

**Comment by skartknet** [comment]
HQ is using it to target elements on the [new tours](https://our.umbraco.com/documentation/Extending/Backoffice-Tours/#element).

**Comment by leekelleher** [comment]
Thanks @skartknet, I didn't know about that, good to know. 😃 

The PR has a merge conflict, the branch probably needs to be rebased. I'll merge it in once it's resolved. 👍

**Comment by skartknet** [comment]
No worries. Do you need me to solve that issue on my side?

**Comment by leekelleher** [comment]
Yes, please. I think you'll need to rebase your `develop` branch against our `develop` branch.
(GitHub has instructions on this if you're not familiar with it - that should be a "Resolve conflicts" button above)

**Comment by skartknet** [comment]
I think it's fixed now.

**Comment by leekelleher** [comment]
Thanks @skartknet, I appreciate it. 👍

I'm not sure why, but the merge has reverted one of our changes, (from commit 9ea76bf93c8d874928f84642ac6ced9a0d7cd9e0) from using `<umb-property-editor>` to the old `<umb-editor>`?

**Comment by leekelleher** [comment]
I've fixed it up on your branch, for this PR.  I'll merge it in now.

Cheers!

**Pull request merged**
